### ISSUE TITLE
Connection to voice channel issue

### ISSUE THREAD

**Issue by Dukemz** [YoussefElshemi/Music-Bot#1]
The bot starts and works, but when trying to get it to join a voice channel, it says "You must be in a voice channel first!" even though I am in one. Any help?

**Comment by typicalGtaTG** [comment]
This code has many issues i think you are better off making your own custom bot

**Comment by blackVanilla** [comment]
@Dukemz upgrade discord.js

**Comment by ghost** [comment]
check your code again. Compare to a working code
